/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Custom.ImagePanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.PopupMenu;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author quock
 */
public class DashboardGUI extends javax.swing.JFrame {

    /**
     * Creates new form DashboardGUI
     */
    public DashboardGUI() {
        initComponents();
        this.setTitle("Trang chủ");
        this.setLocationRelativeTo(null);
        avatar.setLayout(new java.awt.GridBagLayout()); // căn giữa

        ImagePanel avatarImage = new ImagePanel("/images/avatarAccount.png",true);
        avatarImage.setPreferredSize(new java.awt.Dimension(120, 120)); // size avatar

        avatar.add(avatarImage);
        
        lblName.setText("Nguyễn Văn A");
        lblRole.setText("Vai trò: Admin");

        lblName.setForeground(Color.WHITE);
        lblRole.setForeground(new Color(180,180,180));

        lblName.setFont(new Font("Segoe UI", Font.BOLD, 24));
        lblRole.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        lblName.setAlignmentX(Component.CENTER_ALIGNMENT);
        lblRole.setAlignmentX(Component.CENTER_ALIGNMENT);


        JSeparator line = new JSeparator();
        line.setForeground(new Color(80,80,80));
        line.setMaximumSize(new Dimension(200,1));


        // ===== SPACING + ADD COMPONENT =====
        inforPanel.add(lblName);

        inforPanel.add(Box.createVerticalStrut(15));

        inforPanel.add(lblRole);

        inforPanel.add(Box.createVerticalStrut(15));

        inforPanel.add(line);

        inforPanel.add(Box.createVerticalStrut(15));

        inforPanel.add(panelMenu);
        
        JPanel itemProfile = new JPanel();
        itemProfile.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 7, 10));
        itemProfile.setBackground(new Color(31,33,37));
        itemProfile.setMaximumSize(new Dimension(250,40));
        itemProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 0));
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/user.png"));
        Image img = icon.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(img);

        JLabel iconLabel = new JLabel(newIcon);
        JLabel text = new JLabel("Thông tin cá nhân");
        
        text.setForeground(Color.WHITE);
        text.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        itemProfile.add(iconLabel);
        itemProfile.add(text);

        panelMenu.add(itemProfile);
        
        logoutBtn.setLayout(new java.awt.GridBagLayout());
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(20,20,20,20));

        jButton1.setText("Đăng xuất");
        jButton1.setFont(new Font("Segoe UI", Font.BOLD, 18));
        jButton1.setBackground(new Color(255,59,48));
        jButton1.setForeground(Color.WHITE);
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new Dimension(180,45));
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        avatar = new javax.swing.JPanel();
        inforPanel = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSidebar.setBackground(new java.awt.Color(31, 33, 37));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 650));
        panelSidebar.setLayout(new java.awt.BorderLayout());

        avatar.setBackground(new java.awt.Color(31, 33, 37));
        avatar.setPreferredSize(new java.awt.Dimension(250, 200));

        javax.swing.GroupLayout avatarLayout = new javax.swing.GroupLayout(avatar);
        avatar.setLayout(avatarLayout);
        avatarLayout.setHorizontalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        avatarLayout.setVerticalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panelSidebar.add(avatar, java.awt.BorderLayout.NORTH);

        inforPanel.setBackground(new java.awt.Color(31, 33, 37));
        inforPanel.setLayout(new javax.swing.BoxLayout(inforPanel, javax.swing.BoxLayout.Y_AXIS));

        lblName.setText("jLabel1");
        inforPanel.add(lblName);

        lblRole.setText("jLabel2");
        inforPanel.add(lblRole);

        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));
        inforPanel.add(panelMenu);

        panelSidebar.add(inforPanel, java.awt.BorderLayout.CENTER);

        logoutBtn.setBackground(new java.awt.Color(31, 33, 37));

        jButton1.setText("jButton1");
        logoutBtn.add(jButton1);

        panelSidebar.add(logoutBtn, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        panelMain.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        panelMain.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel avatar;
    private javax.swing.JPanel inforPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel logoutBtn;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
